### ISSUE TITLE
polish with different haplotype fasta

### ISSUE THREAD

**Issue by zmz1988** [kishwarshafin/pepper#135]
Hi, thank you for the very nice tool! I have a question about using pepper_margin_deepvariant to polish different haplotypes.

I use flye to do a mix haplotype assembly with Nanopore reads, and then use hapdup with Nanopore reads again to generate the two haplotypes. Now I have hap1.fasta and hap2.fasta, and I would like to use pepper_margin_deepvariant to call the variants against hap1.fasta by using hifi reads. So my questions is when I do margin phasing vcf, can I assume that hap1 in vcf can be applied to hap1.fasta? I guess the question is the same, if I use pepper_margin_deepvariant polish_assembly following [here](https://github.com/kishwarshafin/pepper/blob/r0.4/docs/pipeline_singularity/ONT_polishing_singularity.md), can I assume that PEPPER_MARGIN_DEEPVARIANT_ASM_POLISHED_HAP1.vcf.gz can be applied to hap1.fasta (from hapdup) and PEPPER_MARGIN_DEEPVARIANT_ASM_POLISHED_HAP2.vcf.gz to hap2.fasta (from hapdup)?

Also, may I ask whether we have a way to generate the bam file that are only for homozygous region and hap1 region? I remember I saw something similar in other issues, but I can't find it anymore. Do we need to use pepper_hp?

Thanks!!

**Comment by kishwarshafin** [comment]
@zmz1988 ,

Let's break this down query a little bit so I can help you properly. Are you trying to call variants against hap1.fasta with reads that belong to that specific haplotype or other haplotypes? So the question is, where are the hifi reads coming from? Is it the same individual's reads?

**Comment by zmz1988** [comment]
Thanks for replying me, @kishwarshafin! Oh sorry I forgot to mention, the hifi reads are from the same individual without separating to different haplotypes. Sorry that I also forgot to mention that I study Arabidopsis, presumably homozygous but I found around ~100kb in total heterozygous regions, including where the contigs from mixed haplotype assembly can not be connected. 

So I thought to generate 2 haplotype assembly by Nanopore (>100x), and then use hifi to polish it. (our hifi reads has quite low coverage 10x). But I'm not sure how I can use the vcf file from pepper_margin_deepvariant to do the hifi polish for haplotype 1 and haplotype 2 separately.

**Comment by kishwarshafin** [comment]
@zmz1988 ,

Got it. So, the hapdup output is a phased genome with two haplotypes and now if you want to find haplotype-independent errors then you have to have reads that belong to each haplotype, otherwise, you'll introduce a ton of switch errors back to the assembly.

One thing you can do is align all the reads to hap1.fasta and then call variants and filter all variants that are heterozygous or has a low VAF as they can possibly come from the other haplotype. The reads are from both haplotypes, so you'll see a lot of variants that'll come from the other haplotype, and you'll have to carefully exclude them otherwise you'll homogenize the haplotypes. Polishing haplotypes independently is very tricky and we don't have a proper solution yet.

In the question of generating a bam of homozygous regions, you can use something like dipcall or any other reference-to-reference alignment scheme where you align two haplotypes to each other and exclude regions with variants and you can easily look at regions that do not have any variants or homozygous.

**Comment by zmz1988** [comment]
Thanks a lot @kishwarshafin for the nice suggestions! I'm still wondering why we couldn't directly use the phased vcf from Peper-margin-DV to polish each haplotype? I mean, Peper-margin-DV generates a phased vcf file, and the result of hapdup is a phased genome. Could we simply assume that when SNPs were called and genotypes were phased in the Peper-margin-DV, the haplotype that has the most number of genotypes same as the reference are the haplotype that the reference belongs to? If this assumption is fine, which I'm not sure and would like to hear your advice :), then we could apply the consensus of this haplotype to the reference for polishing?

**Comment by kishwarshafin** [comment]
@zmz1988 , 

I don't think you can assume that the phased VCF and the polished genome correspond one-to-one. After phasing the assembly goes through another round of polishing using Flye and the coordinates etc of the small variants would change. I agree this is a difficult interpretation, if you do so then do it carefully and employ a QC method so you are sure that you are not switching haplotypes.

**Comment by kishwarshafin** [comment]
@zmz1988 ,

I'm closing this issue. If you have further queries or questions, please feel free to reopen this issue.

**Comment by zmz1988** [comment]
Thanks a lot for all the suggestions @kishwarshafin ! I will try and see how much I can polish the heterozygous regions. Sorry for the late reply! I was having a long vacation.
