### ISSUE TITLE
faidx_adjust_position error for pepper polish

### ISSUE THREAD

**Issue by ascheben** [kishwarshafin/pepper#15]
It's my first attempt to run pepper and I executed it as follows on a mammalian shasta assembly:

`pepper polish --bam aligned.bam --fasta Assembly.fasta --model_path /path/to/models/pepper_r941_guppy344_human.pkl --output_file  /path/to/polished --threads 20 --batch_size 128`

Pepper reached about 4% complete and then reported the error below, which led to a crash.

`[E::faidx_adjust_position] The sequence "6" not found`

I checked the aligned.bam file and the Assembly.fasta file and the sequence "6" is present in both files. How do I address this error?

**Comment by kishwarshafin** [comment]
Hi @ascheben ,

This error usually happens when you are using the wrong `Assembly.fasta` file that was not used in `aligned.bam`. Can you please make sure that the `aligned.bam` has the same `Assembly.fasta` as the reference that you have set in `--fasta?` one way to look at is to look at the header of the bam and the fasta file by running:
```bash
samtools view -H aligned.bam 
cat Assembly.fasta.fai
```

If you can paste the output of these two commands here, we can see if the length of contig `6` is consistent in the bam and fasta.

**Comment by ascheben** [comment]
Thanks @kishwarshafin I'm certain the same FASTA was used, but the FASTA does contain thousands of contigs. The outputs of the two commands are attached (>4000 lines so not pasted) and I think it confirms that the same Assembly file with the same sequence headers was used.

[Assembly.header.txt](https://github.com/kishwarshafin/pepper/files/5361471/Assembly.header.txt)
[bam.header.txt](https://github.com/kishwarshafin/pepper/files/5361472/bam.header.txt)

The full set of commands including mapping were:

```
samtools faidx Assembly.fasta
minimap2 -a -t 20 -x map-ont -L Assembly.fasta reads.fastq | samtools sort > aligned.bam
samtools index aligned.bam
pepper polish --bam aligned.bam --fasta Assembly.fasta --model_path /path/to/models/pepper_r941_guppy344_human.pkl --output_file /path/to/polished --threads 20 --batch_size 128
```

**Comment by kishwarshafin** [comment]
Thank you for responding so quickly. The issue is with the `-L` parameter. `PEPPER` parses the CIGAR using the `htslib` function from here:

```bash
uint32_t *cigar = bam_get_cigar(alignment);
```

If you use `-L`, it requires extra support in parsing `CG` tags from the BAM, as described in this issue in htslib:
https://github.com/samtools/htslib/pull/560/files/963091ed9f2a1e0123850cbd3893332e37bfd70a

Which is not implemented in PEPPER. However, if you are using the latest samtools (1.10 or higher) then you shouldn't need `-L` parameter in minimap2 because the newer version of htslibs can store ONT cigars using data types that are not 8bits. 

This is my set of commands that I run for alignment:
```bash
minimap2 -ax map-ont -t 38 Assembly.fasta Reads.fastq | samtools view -hb -F 0x904 > unsorted.bam; \
samtools sort -@38 -o aligned.bam unsorted.bam; \
rm -rf unsorted.bam; \
samtools index -@38 aligned.bam
```

My minimap2 version: 
`2.17-r941`
My samtools version: 
```bash
samtools 1.10
Using htslib 1.10
Copyright (C) 2019 Genome Research Ltd.
```

Please let me know if this fixes the issue.

**Comment by ascheben** [comment]
@kishwarshafin Appreciate your response! And I can confirm that removing the `-L` flag from the minimap2 command and using samtools 1.10 resolved the issue. Pepper ran to completion and output the polished contigs. Thanks!
