### ISSUE TITLE
Is the model using in create consensus reads same as call variant?

### ISSUE THREAD

**Issue by YanJiunLiu** [kishwarshafin/pepper#18]
I have a bam and a fasta data and I am trying to use Pepper in Parallel computing .So I have to really understanding this tool. But  I am confuse in the model , whether the model using in creating  consensus reads same as calling variant running in the same data ? I also trace the code , is 'run inference' in pepper_snp.py same as 'call_consensus' in pepper.py ? In the figure you gave, call consensus and inference are in the same blank , isn't them the same?
<img width="397" alt="截圖 2020-10-29 下午2 56 31" src="https://user-images.githubusercontent.com/63279862/97535701-ff408600-19f6-11eb-9976-f5af20eef2e1.png">

**Comment by kishwarshafin** [comment]
@YanJiunLiu ,

Exciting work! The deep neural network model of `pepper_snp.py` and `pepper.py` are slightly different but the steps are the same as we have described in this pipeline picture. The number of classes we predict with `pepper_snp.py` is different but otherwise, everything else looks exactly the same. 

PEPPER, PEPPER SNP, PEPPER HP all work in three steps: image generation -> run inference/call consensus -> Stitch/Find candidates. The names and underlying logic maybe a bit different but overall the workflow is exactly the same.
