### ISSUE TITLE
models for viral assembly

### ISSUE THREAD

**Issue by chunlinxiao** [kishwarshafin/pepper#34]
Are you going to make Pepper models for viral assemblies?  Thanks

**Comment by kishwarshafin** [comment]
@chunlinxiao , we currently don't have a roadmap for extensive investigation on viral genome assembly polishing. You can possibly take our human genome models and see how it performs on viral genomes out of the box. Otherwise, you can use Medaka. We are more focused on human genome assemblies at this moment as that remains challenging.
