### ISSUE TITLE
Request for recipe singularty file

### ISSUE THREAD

**Issue by davidecanevazzi** [kishwarshafin/pepper#47]
Hi,

I'm working on a cluster and the kernel is too old for executing the instructions in variant_calling_singularity_quickstart.md.
My idea is to rebuild a new container, using an older kernel, but for that I need the recipe (.sif) file. Is it possible to obtain it?

Thank you in advance.

**Comment by kishwarshafin** [comment]
@davidecanevazzi ,

The current version of the docker that we have requires access to an unpublished codebase that is in development and is not tested properly as most of the tests we do reside locally because of the file sizes.

One easier way to get around is to see if you can provide me the configuration of your system and I can create a GCP instance similar to your system, build and provide you a docker. That way, I can make sure you are not using something that is not tested properly. Please let me know if that works for you. If not, I can work on decoupling the current build but will require a little bit of time.

**Comment by davidecanevazzi** [comment]
@kishwarshafin , 
the cluster  runs CentOS 6.7, but it should be compatible with any container which is based on CentOS7. Anything later than that will not run.

**Comment by kishwarshafin** [comment]
@davidecanevazzi , 

It looks like we do test our docker on CentOS 7, can you please run `variant_calling_singularity_quickstart.md` and post the errors you are seeing?

**Comment by davidecanevazzi** [comment]
I get an error after:
singularity exec --bind /usr/lib/locale/ \
> pepper_deepvariant_r0.4.sif \
> run_pepper_margin_deepvariant call_variant \
> -b "${INPUT_DIR}/${BAM}" \
> -f "${INPUT_DIR}/${REF}" \
> -o "${OUTPUT_DIR}" \
> -p "${OUTPUT_PREFIX}" \
> -t ${THREADS} \
> -r chr20:1000000-1020000 \
> --ont

WARNING: underlay of /etc/localtime required more than 50 (103) bind mounts
FATAL: kernel too old

**Comment by kishwarshafin** [comment]
@davidecanevazzi ,

I wanted to let you know that we are working to fix this issue. It seems like it will take a little bit of time. Thanks for your patience.

**Comment by davidecanevazzi** [comment]
@kishwarshafin,
Thank you for the support.  
The tested Ubuntu  base image for singularity in our cluster is Ubuntu 16.04.7 LTS (Xenial Xerus)

**Comment by davidecanevazzi** [comment]
@kishwarshafin,
Are there any updates?

**Comment by kishwarshafin** [comment]
@davidecanevazzi ,

Yes, I have de-coupled the docker scripts from the repo. Testing it now and will send you something by the end of this week.

**Comment by kishwarshafin** [comment]
@davidecanevazzi ,

Can you please send me an email at shafin@ucsc.edu. The files are too big and I can't add them here. It would be helpful if we could take the conversation over our email. I'll close this issue as we are taking this offline.
